apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:oraclelinux9
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: devops
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: passUser
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-devops
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-devops
          emptyDir: {}
