apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:oraclelinux9
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P@ssw0rd"  
        - name: MYSQL_DATABASE
          value: "Database"    
        - name: MYSQL_USER
          value: "user"             
        - name: MYSQL_PASSWORD
          value: "123456"    
        ports:
        - containerPort: 3306
