apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:oraclelinux9
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "your_root_password"
        - name: MYSQL_DATABASE
          value: "your_database_name"
        - name: MYSQL_USER
          value: "your_username"
        - name: MYSQL_PASSWORD
          value: "your_password"
        ports:
        - containerPort: 3306