apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: elestio/pgadmin:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: postgres
  labels:
    app: pgadmin
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pgadmin
