apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: elestio/pgadmin:latest
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "mirzaaqil190@gmail.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "@dm1nistrat0r"
        ports:
        - containerPort: 80
