apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.20-alpine3.20  
        env:
        - name: POSTGRES_DB
          value: "Database"
        - name: POSTGRES_USER
          value: "dbuser"      
        - name: POSTGRES_PASSWORD
          value: "P@ssw0rd"
        ports:
        - containerPort: 5432 
