apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "adminuser"  
        - name: POSTGRES_PASSWORD
          value: "adminpassword"  
        - name: POSTGRES_DB
          value: "mydatabase"  
        ports:
        - containerPort: 5432
