//deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: programming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyhton-app
  template:
    metadata:
      labels:
        app: pyhton-app
    spec:
      containers:
      - name: python-container
        image: python:3.9.20-slim-bullseye
        ports:
        - containerPort: 9797

//service

apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: programming
spec:
  type: LoadBalancer
  ports:
  - port: 9797
    targetPort: 9797
    protocol: TCP
  selector:
    app: python-app