apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: nginx
  namespace: programming
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: python
          image: python:3.9.20-slim-bullseye
          ports:
            - containerPort: 9797
---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
  labels:
    app: python
  namespace: programming
spec:
  type: ClusterIP
  ports:
    - port: 9797
      targetPort: 9797
  selector:
    app: python
