apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: programming
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 9797
      targetPort: 9797
  type: LoadBalancer  # Change this if you need NodePort or ClusterIP instead
