apiVersion: v1
kind: Service
metadata:
  name: class-svc
spec:
  type: LoadBalancer  # Or NodePort if you're not using a cloud provider
  selector:
    app: class
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
