apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
        - name: httpd
          image: httpd:alpine3.20
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: class-service
spec:
  selector:
    app: class
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
