apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
  labels:
    app: class
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
        - name: httpd
          image: httpd:alpine3.20
          ports:
            - containerPort: 80
            - containerPort: 443

apiVersion: v1
kind: Service
metadata:
  name: class-svc
spec:
  type: LoadBalancer
  selector:
    app: class
  ports:
    - name: httpd-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: httpd-443
      protocol: TCP
      port: 443
      targetPort: 443
