apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
spec:
  replicas: 2
  selector:
    matchLabels:
      app: class-app
  template:
    metadata:
      labels:
        app: class-app
    spec:
      containers:
      - name: httpd
        image: httpd:alpine3.20
        ports:
        - containerPort: 80    
        - containerPort: 443   
---
apiVersion: v1
kind: Service
metadata:
  name: class-svc
spec:
  type: LoadBalancer  
  selector:
    app: class-app
  ports:
  - name: http
    protocol: TCP
    port: 80           
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443          
    targetPort: 443
