apiVersion: v1
kind: Service
metadata:
  name: class-svc
spec:
  selector:
    app: class
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http 
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https 
  type: LoadBalancer 