apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
      - name: httpd
        image: httpd:alpine3.20
        ports:
        - containerPort: 80   # Expose port 80 (HTTP)
        - containerPort: 443  # Expose port 443 (HTTPS)
