apiVersion: v1
kind: Service
metadata:
  name: class-svc
spec:
  selector:
    app: class
  ports:
    - name: port1 
      protocol: TCP
      port: 80       
      targetPort: 80   
    - name: port2
      protocol: TCP
      port: 443        
      targetPort: 443  
  type: LoadBalancer