apiVersion: v1
kind: Service
metadata:
  name: class-service
spec:
  selector:
    app: class
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort
