apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: qq2
spec:
  replicas: 3
  selector:
    matchLabels:    
      app: myapp      
  template:
    metadata:
      labels:
        app: myapp   
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80