# controlplane $ cat q8-service
apiVersion: v1
kind: Service
metadata:
  name: cloud-app-svc
  namespace: ca2
spec:
  selector:
    app: cloud-app-01
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80

# controlplane $ cat cloud-app-svc
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapp01
  namespace: ca2
  labels:
    app: cloud-app-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app-01
  template:
    metadata:
      labels:
        app: cloud-app-01
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 80
# controlplane $