apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app01
  namespace: ca2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 80

// service
apiVersion: v1
kind: Service
metadata:
  name: cloud-app-svc
  namespace: ca2
spec:
  selector:
    app: cloud-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP