apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deploy
  namespace: qq3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: python:3.9.20-slim-bullseye
        ports:
        - containerPort: 9797