apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: qq3
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest  # Initial image
        ports:
        - containerPort: 80