apiVersion: v1
kind: Pod
metadata:
  name: limit
  namespace: qq3
spec: 
  containers:
  - name: redis
    image: redis
    resources:
      requests:
        cpu: "0.5"       # 0.5 CPU request
        memory: "500Mi"   # 500 Mi memory request
      limits:
        cpu: "1"          # 1 CPU limit
        memory: "1Gi"     # 1 Gi memory limit
