apiVersion: v1
kind: Pod
metadata:
  name: limit
spec:
  containers: 
    - name: redis-cont
      image: redis
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "1"
          memory: "1Gi"