apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-q5
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine3.20
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"