apiVersion: v1
kind: Pod
metadata:
  name: redis   
spec:
  containers:
  - name: redis
    image: redis:8.0-M01-bookworm          
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"