apiVersion: apps/v1
kind: Deployment
metadata:
  name: web             
  labels:
    app: web  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc   
spec:
  selector:
    app.kubernetes.io/name: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
