#q6.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ca1
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

#q6-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: ca1
spec:
  selector:
    app: web
  ports:
  - name: web-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP