# controlplane $ cat q7
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
# controlplane $ cat q7-service
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prod
spec:
  selector:
    app: app01
  ports:
  - name: node-pyort
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort