apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: qq3
spec:
  containers:
    - name: nginx
      image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: qq3
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: db
